const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';



export {
  ORDER_CREATE_REQUEST,
  ORDER_CREATE_SUCCESS,
  ORDER_CREATE_FAIL,
  ORDER_DETAILS_REQUEST,
  ORDER_DETAILS_SUCCESS,
  ORDER_DETAILS_FAIL,
  ORDER_PAY_REQUEST,
  ORDER_PAY_SUCCESS,
  ORDER_PAY_FAIL,
  ORDER_PAY_RESET,
  ORDER_LIST_MY_REQUEST,
  ORDER_LIST_MY_SUCCESS,
  ORDER_LIST_MY_FAIL,
}